version: '3.8'

services:
  ml-pipeline:
    # Build the image using the Dockerfile in the current directory
    build: .
    container_name: ml_pipeline_container

    environment:
      - PYTHONPATH=/app
    # Ensures Python can find your 'src' folder regardless of which script is running

    
    # 'no' ensures the container stops after the run.sh script completes its work
    # restart: "no"