version: '3.8'

services:
  ml-pipeline:
    # Build the image using the Dockerfile in the current directory
    build: .
    container_name: ml_pipeline_container
  # Ensures Python can find your 'src' folder regardless of which script is running
    environment:
      - PYTHONPATH=/app